import { Boat } from '../types/index';
export const data: Boat[] = [
    {
      num: '1',
      name: 'Angler 330',
      quantity: '3',
      year: '2022',
      producer: 'Angler',
      color: 'красный',
      size: '330',
      seats: '3',
      favorite: false,
    },
    {
        num: '2',
        name: 'BoatMaaster 250',
        quantity: '2',
        year: '2022',
        producer: 'BoatMaster',
        color: 'зеленый',
        size: '250',
        seats: '1',
        favorite: false,
    },
    {
        num: '3',
        name: 'BoatMaaster 300',
        quantity: '5',
        year: '2021',
        producer: 'BoatMaster',
        color: 'серый',
        size: '300',
        seats: '2',
        favorite: false,
    },
    {
        num: '4',
        name: 'BoatMaaster 320',
        quantity: '3',
        year: '2022',
        producer: 'BoatMaaster',
        color: 'зеленый',
        size: '320',
        seats: '3',
        favorite: false,
    },
    {
        num: '5',
        name: 'BoatMaaster 320+',
        quantity: '6',
        year: '2022',
        producer: 'BoatMaaster',
        color: 'серый',
        size: '320',
        seats: '3',
        favorite: true,
    },
    {
        num: '6',
        name: 'Helios 250',
        quantity: '1',
        year: '2020',
        producer: 'Helios',
        color: 'зеленый',
        size: '250',
        seats: '1',
        favorite: false,
    },
    {
        num: '7',
        name: 'Kolibri 250',
        quantity: '5',
        year: '2022',
        producer: 'Kolibri',
        color: 'зеленый',
        size: '250',
        seats: '1',
        favorite: true,
    },
    {
        num: '8',
        name: 'Kolibri 330',
        quantity: '3',
        year: '2020',
        producer: 'Kolibri',
        color: 'зеленый',
        size: '330',
        seats: '3',
        favorite: true,
    },
    {
        num: '9',
        name: 'Адмирал 250',
        quantity: '6',
        year: '2022',
        producer: 'Адмирал',
        color: 'серый',
        size: '250',
        seats: '2',
        favorite: false,
    },
    {
        num: '10',
        name: 'Адмирал 330',
        quantity: '2',
        year: '2022',
        producer: 'Адмирал',
        color: 'серый',
        size: '330',
        seats: '3',
        favorite: false,
    },
    {
        num: '11',
        name: 'Пилот 300',
        quantity: '3',
        year: '2022',
        producer: 'Пилот',
        color: 'кмф',
        size: '300',
        seats: '2',
        favorite: false,
    },
    {
        num: '12',
        name: 'Пилот 300',
        quantity: '2',
        year: '2022',
        producer: 'Пилот',
        color: 'серый',
        size: '300',
        seats: '2',
        favorite: false,
    },
    {
        num: '13',
        name: 'Пилот 320',
        quantity: '3',
        year: '2022',
        producer: 'Пилот',
        color: 'зеленый',
        size: '320',
        seats: '3',
        favorite: false,
    },
    {
        num: '14',
        name: 'Пилот 320',
        quantity: '4',
        year: '2022',
        producer: 'Пилот',
        color: 'кмф',
        size: '320',
        seats: '3',
        favorite: false,
    },
    {
        num: '15',
        name: 'Пилот 330',
        quantity: '6',
        year: '2021',
        producer: 'Пилот',
        color: 'кмф',
        size: '330',
        seats: '3',
        favorite: true,
    },
    {
        num: '16',
        name: 'Таймень 250',
        quantity: '1',
        year: '2020',
        producer: 'Таймень',
        color: 'серый',
        size: '250',
        seats: '1',
        favorite: false,
    },
    {
        num: '17',
        name: 'Таймень 320',
        quantity: '3',
        year: '2020',
        producer: 'Таймень',
        color: 'серый',
        size: '320',
        seats: '3',
        favorite: false,
    },
    {
        num: '18',
        name: 'Таймень 330',
        quantity: '2',
        year: '2022',
        producer: 'Таймень',
        color: 'красный',
        size: '330',
        seats: '3',
        favorite: true,
    },
    {
        num: '19',
        name: 'Феникс 250',
        quantity: '1',
        year: '2020',
        producer: 'Феникс',
        color: 'серый',
        size: '250',
        seats: '1',
        favorite: false,
    },
    {
        num: '20',
        name: 'Феникс 300',
        quantity: '2',
        year: '2020',
        producer: 'Феникс',
        color: 'зеленый',
        size: '300',
        seats: '2',
        favorite: false,
    },
]